// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DemoProto_V1.proto

// Protobuf Java Version: 3.25.3
package ps.demo.protobuf.model;

/**
 * Protobuf type {@code Addr}
 */
public final class Addr extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Addr)
    AddrOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Addr.newBuilder() to construct.
  private Addr(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Addr() {
    line1_ = "";
    line2_ = "";
    line3_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new Addr();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return DemoProtoV1.internal_static_Addr_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return DemoProtoV1.internal_static_Addr_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Addr.class, Builder.class);
  }

  public static final int LINE1_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile Object line1_ = "";
  /**
   * <code>string line1 = 1;</code>
   * @return The line1.
   */
  @Override
  public String getLine1() {
    Object ref = line1_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      line1_ = s;
      return s;
    }
  }
  /**
   * <code>string line1 = 1;</code>
   * @return The bytes for line1.
   */
  @Override
  public com.google.protobuf.ByteString
      getLine1Bytes() {
    Object ref = line1_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      line1_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LINE2_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile Object line2_ = "";
  /**
   * <code>string line2 = 2;</code>
   * @return The line2.
   */
  @Override
  public String getLine2() {
    Object ref = line2_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      line2_ = s;
      return s;
    }
  }
  /**
   * <code>string line2 = 2;</code>
   * @return The bytes for line2.
   */
  @Override
  public com.google.protobuf.ByteString
      getLine2Bytes() {
    Object ref = line2_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      line2_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LINE3_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile Object line3_ = "";
  /**
   * <code>string line3 = 3;</code>
   * @return The line3.
   */
  @Override
  public String getLine3() {
    Object ref = line3_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      line3_ = s;
      return s;
    }
  }
  /**
   * <code>string line3 = 3;</code>
   * @return The bytes for line3.
   */
  @Override
  public com.google.protobuf.ByteString
      getLine3Bytes() {
    Object ref = line3_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      line3_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERSION_FIELD_NUMBER = 4;
  private long version_ = 0L;
  /**
   * <code>int64 version = 4;</code>
   * @return The version.
   */
  @Override
  public long getVersion() {
    return version_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(line1_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, line1_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(line2_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, line2_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(line3_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, line3_);
    }
    if (version_ != 0L) {
      output.writeInt64(4, version_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(line1_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, line1_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(line2_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, line2_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(line3_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, line3_);
    }
    if (version_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, version_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Addr)) {
      return super.equals(obj);
    }
    Addr other = (Addr) obj;

    if (!getLine1()
        .equals(other.getLine1())) return false;
    if (!getLine2()
        .equals(other.getLine2())) return false;
    if (!getLine3()
        .equals(other.getLine3())) return false;
    if (getVersion()
        != other.getVersion()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LINE1_FIELD_NUMBER;
    hash = (53 * hash) + getLine1().hashCode();
    hash = (37 * hash) + LINE2_FIELD_NUMBER;
    hash = (53 * hash) + getLine2().hashCode();
    hash = (37 * hash) + LINE3_FIELD_NUMBER;
    hash = (53 * hash) + getLine3().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getVersion());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Addr parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Addr parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Addr parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Addr parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Addr parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Addr parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Addr parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Addr parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static Addr parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static Addr parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Addr parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Addr parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Addr prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Addr}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Addr)
      AddrOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DemoProtoV1.internal_static_Addr_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DemoProtoV1.internal_static_Addr_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Addr.class, Builder.class);
    }

    // Construct using ps.demo.protobuf.model.Addr.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      line1_ = "";
      line2_ = "";
      line3_ = "";
      version_ = 0L;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return DemoProtoV1.internal_static_Addr_descriptor;
    }

    @Override
    public Addr getDefaultInstanceForType() {
      return Addr.getDefaultInstance();
    }

    @Override
    public Addr build() {
      Addr result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public Addr buildPartial() {
      Addr result = new Addr(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(Addr result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.line1_ = line1_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.line2_ = line2_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.line3_ = line3_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.version_ = version_;
      }
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Addr) {
        return mergeFrom((Addr)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Addr other) {
      if (other == Addr.getDefaultInstance()) return this;
      if (!other.getLine1().isEmpty()) {
        line1_ = other.line1_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getLine2().isEmpty()) {
        line2_ = other.line2_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getLine3().isEmpty()) {
        line3_ = other.line3_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getVersion() != 0L) {
        setVersion(other.getVersion());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              line1_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              line2_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              line3_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              version_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object line1_ = "";
    /**
     * <code>string line1 = 1;</code>
     * @return The line1.
     */
    public String getLine1() {
      Object ref = line1_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        line1_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string line1 = 1;</code>
     * @return The bytes for line1.
     */
    public com.google.protobuf.ByteString
        getLine1Bytes() {
      Object ref = line1_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        line1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string line1 = 1;</code>
     * @param value The line1 to set.
     * @return This builder for chaining.
     */
    public Builder setLine1(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      line1_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string line1 = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLine1() {
      line1_ = getDefaultInstance().getLine1();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string line1 = 1;</code>
     * @param value The bytes for line1 to set.
     * @return This builder for chaining.
     */
    public Builder setLine1Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      line1_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private Object line2_ = "";
    /**
     * <code>string line2 = 2;</code>
     * @return The line2.
     */
    public String getLine2() {
      Object ref = line2_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        line2_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string line2 = 2;</code>
     * @return The bytes for line2.
     */
    public com.google.protobuf.ByteString
        getLine2Bytes() {
      Object ref = line2_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        line2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string line2 = 2;</code>
     * @param value The line2 to set.
     * @return This builder for chaining.
     */
    public Builder setLine2(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      line2_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string line2 = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLine2() {
      line2_ = getDefaultInstance().getLine2();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string line2 = 2;</code>
     * @param value The bytes for line2 to set.
     * @return This builder for chaining.
     */
    public Builder setLine2Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      line2_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private Object line3_ = "";
    /**
     * <code>string line3 = 3;</code>
     * @return The line3.
     */
    public String getLine3() {
      Object ref = line3_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        line3_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string line3 = 3;</code>
     * @return The bytes for line3.
     */
    public com.google.protobuf.ByteString
        getLine3Bytes() {
      Object ref = line3_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        line3_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string line3 = 3;</code>
     * @param value The line3 to set.
     * @return This builder for chaining.
     */
    public Builder setLine3(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      line3_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string line3 = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLine3() {
      line3_ = getDefaultInstance().getLine3();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string line3 = 3;</code>
     * @param value The bytes for line3 to set.
     * @return This builder for chaining.
     */
    public Builder setLine3Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      line3_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private long version_ ;
    /**
     * <code>int64 version = 4;</code>
     * @return The version.
     */
    @Override
    public long getVersion() {
      return version_;
    }
    /**
     * <code>int64 version = 4;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(long value) {

      version_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int64 version = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      bitField0_ = (bitField0_ & ~0x00000008);
      version_ = 0L;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Addr)
  }

  // @@protoc_insertion_point(class_scope:Addr)
  private static final Addr DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Addr();
  }

  public static Addr getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Addr>
      PARSER = new com.google.protobuf.AbstractParser<Addr>() {
    @Override
    public Addr parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Addr> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Addr> getParserForType() {
    return PARSER;
  }

  @Override
  public Addr getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

