// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DemoProto_V1.proto

// Protobuf Java Version: 3.25.3
package ps.demo.uploadspringbatch.protobuf.model;

public interface AddrOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Addr)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string line1 = 1;</code>
   * @return The line1.
   */
  String getLine1();
  /**
   * <code>string line1 = 1;</code>
   * @return The bytes for line1.
   */
  com.google.protobuf.ByteString
      getLine1Bytes();

  /**
   * <code>string line2 = 2;</code>
   * @return The line2.
   */
  String getLine2();
  /**
   * <code>string line2 = 2;</code>
   * @return The bytes for line2.
   */
  com.google.protobuf.ByteString
      getLine2Bytes();

  /**
   * <code>string line3 = 3;</code>
   * @return The line3.
   */
  String getLine3();
  /**
   * <code>string line3 = 3;</code>
   * @return The bytes for line3.
   */
  com.google.protobuf.ByteString
      getLine3Bytes();

  /**
   * <code>int64 version = 4;</code>
   * @return The version.
   */
  long getVersion();
}
