// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Training.proto

// Protobuf Java Version: 3.25.3
package ps.demo.uploadspringbatch.protobuf.model;

public interface StudentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Student)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string first_name = 2;</code>
   * @return The firstName.
   */
  String getFirstName();
  /**
   * <code>string first_name = 2;</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string last_name = 3;</code>
   * @return The lastName.
   */
  String getLastName();
  /**
   * <code>string last_name = 3;</code>
   * @return The bytes for lastName.
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>string email = 4;</code>
   * @return The email.
   */
  String getEmail();
  /**
   * <code>string email = 4;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>repeated .Student.PhoneNumber phone = 5;</code>
   */
  java.util.List<Student.PhoneNumber>
      getPhoneList();
  /**
   * <code>repeated .Student.PhoneNumber phone = 5;</code>
   */
  Student.PhoneNumber getPhone(int index);
  /**
   * <code>repeated .Student.PhoneNumber phone = 5;</code>
   */
  int getPhoneCount();
  /**
   * <code>repeated .Student.PhoneNumber phone = 5;</code>
   */
  java.util.List<? extends Student.PhoneNumberOrBuilder>
      getPhoneOrBuilderList();
  /**
   * <code>repeated .Student.PhoneNumber phone = 5;</code>
   */
  Student.PhoneNumberOrBuilder getPhoneOrBuilder(
      int index);
}
