// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Training.proto

// Protobuf Java Version: 3.25.3
package ps.demo.commonlibx.protobuf.model;

public interface CourseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Course)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string course_name = 2;</code>
   * @return The courseName.
   */
  String getCourseName();
  /**
   * <code>string course_name = 2;</code>
   * @return The bytes for courseName.
   */
  com.google.protobuf.ByteString
      getCourseNameBytes();

  /**
   * <code>repeated .Student student = 3;</code>
   */
  java.util.List<Student>
      getStudentList();
  /**
   * <code>repeated .Student student = 3;</code>
   */
  Student getStudent(int index);
  /**
   * <code>repeated .Student student = 3;</code>
   */
  int getStudentCount();
  /**
   * <code>repeated .Student student = 3;</code>
   */
  java.util.List<? extends StudentOrBuilder>
      getStudentOrBuilderList();
  /**
   * <code>repeated .Student student = 3;</code>
   */
  StudentOrBuilder getStudentOrBuilder(
      int index);
}
