// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DemoProto_V1.proto

// Protobuf Java Version: 3.25.3
package ps.demo.commonlibx.protobuf.model;

/**
 * Protobuf type {@code Person}
 */
public final class Person extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Person)
    PersonOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Person.newBuilder() to construct.
  private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Person() {
    name_ = "";
    nickname_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    email_ = "";
    peType_ = 0;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new Person();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return DemoProtoV1.internal_static_Person_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return DemoProtoV1.internal_static_Person_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Person.class, Builder.class);
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile Object name_ = "";
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @Override
  public String getName() {
    Object ref = name_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    Object ref = name_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NICKNAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList nickname_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string nickname = 2;</code>
   * @return A list containing the nickname.
   */
  public com.google.protobuf.ProtocolStringList
      getNicknameList() {
    return nickname_;
  }
  /**
   * <code>repeated string nickname = 2;</code>
   * @return The count of nickname.
   */
  public int getNicknameCount() {
    return nickname_.size();
  }
  /**
   * <code>repeated string nickname = 2;</code>
   * @param index The index of the element to return.
   * @return The nickname at the given index.
   */
  public String getNickname(int index) {
    return nickname_.get(index);
  }
  /**
   * <code>repeated string nickname = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the nickname at the given index.
   */
  public com.google.protobuf.ByteString
      getNicknameBytes(int index) {
    return nickname_.getByteString(index);
  }

  public static final int ID_FIELD_NUMBER = 3;
  private int id_ = 0;
  /**
   * <code>int32 id = 3;</code>
   * @return The id.
   */
  @Override
  public int getId() {
    return id_;
  }

  public static final int EMAIL_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile Object email_ = "";
  /**
   * <code>string email = 4;</code>
   * @return The email.
   */
  @Override
  public String getEmail() {
    Object ref = email_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      email_ = s;
      return s;
    }
  }
  /**
   * <code>string email = 4;</code>
   * @return The bytes for email.
   */
  @Override
  public com.google.protobuf.ByteString
      getEmailBytes() {
    Object ref = email_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PETYPE_FIELD_NUMBER = 5;
  private int peType_ = 0;
  /**
   * <code>.PeType peType = 5;</code>
   * @return The enum numeric value on the wire for peType.
   */
  @Override public int getPeTypeValue() {
    return peType_;
  }
  /**
   * <code>.PeType peType = 5;</code>
   * @return The peType.
   */
  @Override public PeType getPeType() {
    PeType result = PeType.forNumber(peType_);
    return result == null ? PeType.UNRECOGNIZED : result;
  }

  public static final int ADDR_FIELD_NUMBER = 6;
  private Addr addr_;
  /**
   * <code>.Addr addr = 6;</code>
   * @return Whether the addr field is set.
   */
  @Override
  public boolean hasAddr() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.Addr addr = 6;</code>
   * @return The addr.
   */
  @Override
  public Addr getAddr() {
    return addr_ == null ? Addr.getDefaultInstance() : addr_;
  }
  /**
   * <code>.Addr addr = 6;</code>
   */
  @Override
  public AddrOrBuilder getAddrOrBuilder() {
    return addr_ == null ? Addr.getDefaultInstance() : addr_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    for (int i = 0; i < nickname_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nickname_.getRaw(i));
    }
    if (id_ != 0) {
      output.writeInt32(3, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, email_);
    }
    if (peType_ != PeType.INVALID.getNumber()) {
      output.writeEnum(5, peType_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(6, getAddr());
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < nickname_.size(); i++) {
        dataSize += computeStringSizeNoTag(nickname_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getNicknameList().size();
    }
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, email_);
    }
    if (peType_ != PeType.INVALID.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, peType_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getAddr());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Person)) {
      return super.equals(obj);
    }
    Person other = (Person) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getNicknameList()
        .equals(other.getNicknameList())) return false;
    if (getId()
        != other.getId()) return false;
    if (!getEmail()
        .equals(other.getEmail())) return false;
    if (peType_ != other.peType_) return false;
    if (hasAddr() != other.hasAddr()) return false;
    if (hasAddr()) {
      if (!getAddr()
          .equals(other.getAddr())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (getNicknameCount() > 0) {
      hash = (37 * hash) + NICKNAME_FIELD_NUMBER;
      hash = (53 * hash) + getNicknameList().hashCode();
    }
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getEmail().hashCode();
    hash = (37 * hash) + PETYPE_FIELD_NUMBER;
    hash = (53 * hash) + peType_;
    if (hasAddr()) {
      hash = (37 * hash) + ADDR_FIELD_NUMBER;
      hash = (53 * hash) + getAddr().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Person parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Person parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Person parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Person parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Person parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Person parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Person parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Person parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static Person parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static Person parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Person parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Person parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Person prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Person}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Person)
      PersonOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DemoProtoV1.internal_static_Person_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DemoProtoV1.internal_static_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Person.class, Builder.class);
    }

    // Construct using ps.demo.protobuf.model.Person.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAddrFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      nickname_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      id_ = 0;
      email_ = "";
      peType_ = 0;
      addr_ = null;
      if (addrBuilder_ != null) {
        addrBuilder_.dispose();
        addrBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return DemoProtoV1.internal_static_Person_descriptor;
    }

    @Override
    public Person getDefaultInstanceForType() {
      return Person.getDefaultInstance();
    }

    @Override
    public Person build() {
      Person result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public Person buildPartial() {
      Person result = new Person(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(Person result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        nickname_.makeImmutable();
        result.nickname_ = nickname_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.email_ = email_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.peType_ = peType_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.addr_ = addrBuilder_ == null
            ? addr_
            : addrBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Person) {
        return mergeFrom((Person)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Person other) {
      if (other == Person.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.nickname_.isEmpty()) {
        if (nickname_.isEmpty()) {
          nickname_ = other.nickname_;
          bitField0_ |= 0x00000002;
        } else {
          ensureNicknameIsMutable();
          nickname_.addAll(other.nickname_);
        }
        onChanged();
      }
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getEmail().isEmpty()) {
        email_ = other.email_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.peType_ != 0) {
        setPeTypeValue(other.getPeTypeValue());
      }
      if (other.hasAddr()) {
        mergeAddr(other.getAddr());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              String s = input.readStringRequireUtf8();
              ensureNicknameIsMutable();
              nickname_.add(s);
              break;
            } // case 18
            case 24: {
              id_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              email_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              peType_ = input.readEnum();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              input.readMessage(
                  getAddrFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public String getName() {
      Object ref = name_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList nickname_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureNicknameIsMutable() {
      if (!nickname_.isModifiable()) {
        nickname_ = new com.google.protobuf.LazyStringArrayList(nickname_);
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>repeated string nickname = 2;</code>
     * @return A list containing the nickname.
     */
    public com.google.protobuf.ProtocolStringList
        getNicknameList() {
      nickname_.makeImmutable();
      return nickname_;
    }
    /**
     * <code>repeated string nickname = 2;</code>
     * @return The count of nickname.
     */
    public int getNicknameCount() {
      return nickname_.size();
    }
    /**
     * <code>repeated string nickname = 2;</code>
     * @param index The index of the element to return.
     * @return The nickname at the given index.
     */
    public String getNickname(int index) {
      return nickname_.get(index);
    }
    /**
     * <code>repeated string nickname = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the nickname at the given index.
     */
    public com.google.protobuf.ByteString
        getNicknameBytes(int index) {
      return nickname_.getByteString(index);
    }
    /**
     * <code>repeated string nickname = 2;</code>
     * @param index The index to set the value at.
     * @param value The nickname to set.
     * @return This builder for chaining.
     */
    public Builder setNickname(
        int index, String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureNicknameIsMutable();
      nickname_.set(index, value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string nickname = 2;</code>
     * @param value The nickname to add.
     * @return This builder for chaining.
     */
    public Builder addNickname(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureNicknameIsMutable();
      nickname_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string nickname = 2;</code>
     * @param values The nickname to add.
     * @return This builder for chaining.
     */
    public Builder addAllNickname(
        Iterable<String> values) {
      ensureNicknameIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, nickname_);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string nickname = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNickname() {
      nickname_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string nickname = 2;</code>
     * @param value The bytes of the nickname to add.
     * @return This builder for chaining.
     */
    public Builder addNicknameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureNicknameIsMutable();
      nickname_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int id_ ;
    /**
     * <code>int32 id = 3;</code>
     * @return The id.
     */
    @Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 3;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {

      id_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      id_ = 0;
      onChanged();
      return this;
    }

    private Object email_ = "";
    /**
     * <code>string email = 4;</code>
     * @return The email.
     */
    public String getEmail() {
      Object ref = email_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        email_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string email = 4;</code>
     * @return The bytes for email.
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string email = 4;</code>
     * @param value The email to set.
     * @return This builder for chaining.
     */
    public Builder setEmail(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      email_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string email = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmail() {
      email_ = getDefaultInstance().getEmail();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string email = 4;</code>
     * @param value The bytes for email to set.
     * @return This builder for chaining.
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      email_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private int peType_ = 0;
    /**
     * <code>.PeType peType = 5;</code>
     * @return The enum numeric value on the wire for peType.
     */
    @Override public int getPeTypeValue() {
      return peType_;
    }
    /**
     * <code>.PeType peType = 5;</code>
     * @param value The enum numeric value on the wire for peType to set.
     * @return This builder for chaining.
     */
    public Builder setPeTypeValue(int value) {
      peType_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.PeType peType = 5;</code>
     * @return The peType.
     */
    @Override
    public PeType getPeType() {
      PeType result = PeType.forNumber(peType_);
      return result == null ? PeType.UNRECOGNIZED : result;
    }
    /**
     * <code>.PeType peType = 5;</code>
     * @param value The peType to set.
     * @return This builder for chaining.
     */
    public Builder setPeType(PeType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000010;
      peType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.PeType peType = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPeType() {
      bitField0_ = (bitField0_ & ~0x00000010);
      peType_ = 0;
      onChanged();
      return this;
    }

    private Addr addr_;
    private com.google.protobuf.SingleFieldBuilderV3<
        Addr, Addr.Builder, AddrOrBuilder> addrBuilder_;
    /**
     * <code>.Addr addr = 6;</code>
     * @return Whether the addr field is set.
     */
    public boolean hasAddr() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>.Addr addr = 6;</code>
     * @return The addr.
     */
    public Addr getAddr() {
      if (addrBuilder_ == null) {
        return addr_ == null ? Addr.getDefaultInstance() : addr_;
      } else {
        return addrBuilder_.getMessage();
      }
    }
    /**
     * <code>.Addr addr = 6;</code>
     */
    public Builder setAddr(Addr value) {
      if (addrBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        addr_ = value;
      } else {
        addrBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.Addr addr = 6;</code>
     */
    public Builder setAddr(
        Addr.Builder builderForValue) {
      if (addrBuilder_ == null) {
        addr_ = builderForValue.build();
      } else {
        addrBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.Addr addr = 6;</code>
     */
    public Builder mergeAddr(Addr value) {
      if (addrBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          addr_ != null &&
          addr_ != Addr.getDefaultInstance()) {
          getAddrBuilder().mergeFrom(value);
        } else {
          addr_ = value;
        }
      } else {
        addrBuilder_.mergeFrom(value);
      }
      if (addr_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.Addr addr = 6;</code>
     */
    public Builder clearAddr() {
      bitField0_ = (bitField0_ & ~0x00000020);
      addr_ = null;
      if (addrBuilder_ != null) {
        addrBuilder_.dispose();
        addrBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.Addr addr = 6;</code>
     */
    public Addr.Builder getAddrBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getAddrFieldBuilder().getBuilder();
    }
    /**
     * <code>.Addr addr = 6;</code>
     */
    public AddrOrBuilder getAddrOrBuilder() {
      if (addrBuilder_ != null) {
        return addrBuilder_.getMessageOrBuilder();
      } else {
        return addr_ == null ?
            Addr.getDefaultInstance() : addr_;
      }
    }
    /**
     * <code>.Addr addr = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Addr, Addr.Builder, AddrOrBuilder>
        getAddrFieldBuilder() {
      if (addrBuilder_ == null) {
        addrBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Addr, Addr.Builder, AddrOrBuilder>(
                getAddr(),
                getParentForChildren(),
                isClean());
        addr_ = null;
      }
      return addrBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Person)
  }

  // @@protoc_insertion_point(class_scope:Person)
  private static final Person DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Person();
  }

  public static Person getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Person>
      PARSER = new com.google.protobuf.AbstractParser<Person>() {
    @Override
    public Person parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Person> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Person> getParserForType() {
    return PARSER;
  }

  @Override
  public Person getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

