// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DemoProto_V1.proto

// Protobuf Java Version: 3.25.3
package ps.demo.commonlibx.protobuf.model;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>repeated string nickname = 2;</code>
   * @return A list containing the nickname.
   */
  java.util.List<String>
      getNicknameList();
  /**
   * <code>repeated string nickname = 2;</code>
   * @return The count of nickname.
   */
  int getNicknameCount();
  /**
   * <code>repeated string nickname = 2;</code>
   * @param index The index of the element to return.
   * @return The nickname at the given index.
   */
  String getNickname(int index);
  /**
   * <code>repeated string nickname = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the nickname at the given index.
   */
  com.google.protobuf.ByteString
      getNicknameBytes(int index);

  /**
   * <code>int32 id = 3;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string email = 4;</code>
   * @return The email.
   */
  String getEmail();
  /**
   * <code>string email = 4;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>.PeType peType = 5;</code>
   * @return The enum numeric value on the wire for peType.
   */
  int getPeTypeValue();
  /**
   * <code>.PeType peType = 5;</code>
   * @return The peType.
   */
  PeType getPeType();

  /**
   * <code>.Addr addr = 6;</code>
   * @return Whether the addr field is set.
   */
  boolean hasAddr();
  /**
   * <code>.Addr addr = 6;</code>
   * @return The addr.
   */
  Addr getAddr();
  /**
   * <code>.Addr addr = 6;</code>
   */
  AddrOrBuilder getAddrOrBuilder();
}
